---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: snapshots-manager
  namespace: velero
  labels:
    app: velero
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  schedule: "* 6 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: velero
            istio-prometheus-ignore: "true"
        spec:
          imagePullSecrets:
            - name: staffbase-artifactory
          containers:
            - name: python-container
              image: staffbase.jfrog.io/sb-images-dockerhub-proxy/python:3.11-alpine
              env:
                - name: RESOURCE_GROUP
                  value: prod-de1-nodepool
                - name: DESTINATION_REGION
                  value: "Germany North"
                - name: DESTINATION_RESOURCE_GROUP
                  valueFrom:
                    secretKeyRef:
                      key: AZURE_RESOURCE_GROUP
                      name: snapshots-manager-script-credentails
                - name: SUBSCRIPTION_ID
                  valueFrom:
                    secretKeyRef:
                      key: AZURE_SUBSCRIPTION_ID
                      name: snapshots-manager-script-credentails
                - name: CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      key: AZURE_CLIENT_ID
                      name: snapshots-manager-script-credentails
                - name: CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      key: AZURE_CLIENT_SECRET
                      name: snapshots-manager-script-credentails
                - name: TENANT_ID
                  valueFrom:
                    secretKeyRef:
                      key: AZURE_TENANT_ID
                      name: snapshots-manager-script-credentails
              command:
                - /bin/sh
                - -ce
                - python3 /mnt/snapshots-manager.py
              imagePullPolicy: IfNotPresent
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: [ALL]
                privileged: false
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              resources:
                requests:
                  memory: "100Mi"
                  cpu: "50m"
                limits:
                  memory: "100Mi"
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            fsGroup: 1001
